name: vertical_steps_indicator
description: "A simple flutter steps indicator widget."
version: 0.0.1
homepage: https://pub.dev/packages/vertical_steps_indicator
repository: https://github.com/atkabdlh/vertical_steps_indicator
issue_tracker: https://github.com/atkabdlh/vertical_steps_indicator/issues

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - example_images/

license: MIT
